/*
 * Extracts the Sentinel analysis engine (fetching, classification, architecture analysis,
 * insights) from the legacy single-file ../index.html into src/engine/engine.generated.js.
 *
 * The legacy page stays the source of truth for the detection logic; run
 *   npm run extract-engine
 * after changing it. DOM/UI helpers are replaced by the shims in src/engine/shims.js.
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import * as acorn from 'acorn'
import * as walk from 'acorn-walk'

const here = path.dirname(fileURLToPath(import.meta.url))
const htmlPath = path.resolve(here, '../../index.html')
const outPath = path.resolve(here, '../src/engine/engine.generated.js')

/** Functions/constants supplied by src/engine/shims.js instead of the legacy DOM versions. */
const PROVIDED = new Set([
  'STATE', 'log', 'setStatus', 'escapeHtml', 'ghHeaders', 'updateRateLimit',
  'updateInventoryIndicator', 'ensureYaml', 'ensureD3', '$', '$$', 'toggleLoader', 'debounce',
])

/** Public entry points; everything they depend on is pulled in automatically. */
const ROOTS = [
  'listSolutions', 'detectDefaultBranch', 'listSolutionJsonPaths', 'fetchSolutionFiles',
  'buildArtifacts', 'extractSolutionMeta', 'analyzeSolutionArchitecture', 'analyzeCreateUiDefinition',
  'buildSolutionInsights', 'insReconcileArchitecture',
  'INS_METHODS', 'INS_ARCH_CATEGORIES', 'INS_TACTICS',
]

const html = fs.readFileSync(htmlPath, 'utf8')
const scripts = [...html.matchAll(/<script(?:\s+id="[^"]*")?>([\s\S]*?)<\/script>/g)].map((m) => m[1])

/** name -> { code, order, refs } (last declaration wins, like in the browser) */
const decls = new Map()
let order = 0

for (const code of scripts) {
  let ast
  try {
    ast = acorn.parse(code, { ecmaVersion: 'latest', sourceType: 'script' })
  } catch (e) {
    console.warn('skip script (parse error):', e.message)
    continue
  }
  for (const node of ast.body) {
    let names = []
    if (node.type === 'FunctionDeclaration') names = [node.id.name]
    else if (node.type === 'VariableDeclaration')
      names = node.declarations.flatMap((d) => (d.id.type === 'Identifier' ? [d.id.name] : []))
    else continue

    const refs = new Set()
    walk.full(node, (n) => {
      if (n.type === 'Identifier') refs.add(n.name)
    })
    const text = code.slice(node.start, node.end)
    for (const name of names) decls.set(name, { code: text, order: order++, refs, names })
  }
}

const needed = new Set()
const queue = [...ROOTS]
while (queue.length) {
  const name = queue.pop()
  if (needed.has(name) || PROVIDED.has(name)) continue
  const d = decls.get(name)
  if (!d) {
    if (ROOTS.includes(name)) console.warn('missing root:', name)
    continue
  }
  needed.add(name)
  for (const r of d.refs) if (decls.has(r) && !needed.has(r)) queue.push(r)
}

// Emit each distinct statement once, in source order.
const statements = new Map()
for (const name of needed) {
  const d = decls.get(name)
  statements.set(d.code, d)
}
const sorted = [...statements.values()].sort((a, b) => a.order - b.order)

let body = sorted.map((d) => d.code).join('\n\n')

// Replace the DOM-driven progress text with a callback.
body = body.replace(/if\(done%20===0\) setStatus\(`Fetched \$\{done\}\/\$\{paths\.length\} files\.\.\.`\);/, 'onProgress(done,paths.length);')
if (!body.includes('onProgress(done,paths.length)')) console.warn('progress hook not applied')
body = body.replace(/const out=fetched\.filter\(Boolean\);/, 'onProgress(paths.length,paths.length);\n  const out=fetched.filter(Boolean);')

// Remaining browser globals indicate a missed UI dependency.
const suspicious = [...body.matchAll(/\b(document|window|localStorage)\b|\$\$?\(/g)].map((m) => m[0])
if (suspicious.length) console.warn('browser globals still referenced:', [...new Set(suspicious)].join(', '))

const exported = [...needed].filter((n) => ROOTS.includes(n) || /^(ins|INS_)/.test(n) || /^(armResolve|classifyArtifact|normalizeMetaList)$/.test(n))

const out = `// @ts-nocheck
/* AUTO-GENERATED by scripts/extract-engine.mjs from ../index.html — do not edit by hand. */
import { STATE, log, setStatus, escapeHtml, ghHeaders, updateRateLimit, updateInventoryIndicator, ensureYaml, onProgress } from './shims.js'

${body}

export { ${exported.join(', ')} }
`
fs.mkdirSync(path.dirname(outPath), { recursive: true })
fs.writeFileSync(outPath, out)
console.log(`engine written: ${path.relative(process.cwd(), outPath)}  (${needed.size} declarations, ${(out.length / 1024).toFixed(0)} KB)`)
console.log('exports:', exported.length)
